import os
# print(dir(os))
# print(os.getcwd())
# os.chdir("C://")
# print(os.getcwd())
# f=open("Paras.txt")
# print(os.listdir())
# print(os.listdir("C://"))
# os.mkdir("Bhutki")
# os.mkdir("This/that") #Error
# os.makedirs("This/That")
# os.rename("Paras.txt", "Bhutkii.txt")
# print(os.environ.get('Path'))
# print(os.path.join("C:/","//Paras2.txt"))
# print(os.path.exists("C://"))
# print(os.path.exists("C://ProgramData"))
# print(os.path.exists("C://ProgramDatafdsjil"))
print(os.path.isdir("C://ProgramData"))
print(os.path.isfile("C://ProgramData"))